version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    
    volumes:
      - ./backend:/app # Mount the backend directory to /app in the container
      - /app/node_modules # Prevent overwriting node_modules with host's empty directory
  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s    # check every 10 seconds
      timeout: 5s      # if it takes more than 5 seconds to respond, consider it a failure
      retries: 3       # if it fails 3 times in a row, mark it as unhealthy
      start_period: 5s # give the app 5 seconds to start before checking its status

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    
    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

      # let the frontend folder on our real machine 
      # be mounted to /app inside the container in real-time. 
      # The separate line for node_modules is telling Docker 
      # "don't mount node_modules from the host into the container 
      # because it needs to use the Linux version inside there."